
import { GoogleGenAI, Type } from "@google/genai";
import { InfographicType } from "./types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY! });

export const generateInfographics = async (topic: string) => {
  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-preview',
    contents: `Generate 4 distinct infographic concepts for the topic: "${topic}". 
    Each infographic must be one of the following types: statistical, process, comparison, or educational.
    Ensure variety: one of each type.
    Choose professional accent colors for each (hex codes).
    Make the content factual and engaging.`,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          infographics: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                id: { type: Type.STRING },
                type: { 
                  type: Type.STRING, 
                  description: "Must be one of: statistical, process, comparison, educational" 
                },
                title: { type: Type.STRING },
                subtitle: { type: Type.STRING },
                summary: { type: Type.STRING },
                accentColor: { type: Type.STRING },
                stats: {
                  type: Type.ARRAY,
                  items: {
                    type: Type.OBJECT,
                    properties: {
                      label: { type: Type.STRING },
                      value: { type: Type.NUMBER },
                      unit: { type: Type.STRING }
                    },
                    required: ["label", "value"]
                  }
                },
                steps: {
                  type: Type.ARRAY,
                  items: {
                    type: Type.OBJECT,
                    properties: {
                      title: { type: Type.STRING },
                      description: { type: Type.STRING }
                    },
                    required: ["title", "description"]
                  }
                },
                comparison: {
                  type: Type.OBJECT,
                  properties: {
                    sideA: {
                      type: Type.OBJECT,
                      properties: {
                        title: { type: Type.STRING },
                        points: { type: Type.ARRAY, items: { type: Type.STRING } }
                      }
                    },
                    sideB: {
                      type: Type.OBJECT,
                      properties: {
                        title: { type: Type.STRING },
                        points: { type: Type.ARRAY, items: { type: Type.STRING } }
                      }
                    }
                  }
                },
                points: {
                  type: Type.ARRAY,
                  items: {
                    type: Type.OBJECT,
                    properties: {
                      title: { type: Type.STRING },
                      text: { type: Type.STRING }
                    }
                  }
                }
              },
              required: ["id", "type", "title", "subtitle", "summary", "accentColor"]
            }
          }
        },
        required: ["infographics"]
      }
    }
  });

  try {
    const data = JSON.parse(response.text);
    return data.infographics;
  } catch (error) {
    console.error("Failed to parse Gemini response", error);
    throw new Error("Invalid response from AI service");
  }
};

export const editImageWithAI = async (base64Image: string, mimeType: string, prompt: string) => {
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Image,
            mimeType: mimeType,
          },
        },
        {
          text: prompt,
        },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
    }
  }
  
  throw new Error("No image was generated by the model.");
};
